In [59]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib as plt
from shared import init_analyse  #initiële analyse functie
#Importeren van libraries

# 1 ***Analyse sales data***

In dit onderdeel importeren en analyseren we de salesdata met behulp van pandas

### 1.1 Importeren en inlezen dataset

In [60]:
sales_path= Path(r"Data\Contoso_Sales.csv")
#Inlezen sales.csv
sales_df = pd.read_csv(sales_path,
                       decimal=",")
#Dataframe koppelen aan variabele
#Decimal argument meegegeven, omdat pandas standaard . als delimiter ziet.

Data is met behulp van pathlib en pandas ingelezen.  
Bij het inlezen ontstond initieel een dtypewarning voor de kolommen ReturnAmount en DiscountAmount. 
Door bij het inlezen het decimal teken mee te geven wordt deze fout verholpen en worden floats gelijk correct ingelezen.

### 1.2. Eerste analyse
Hier wordt de algehele dataset geanalyseerd op afwijkingen, waar hierna op groter detailniveau naar gekeken wordt.

In [61]:
sales_df.info()
#Eerste data over kolommen opvragen

<class 'pandas.DataFrame'>
RangeIndex: 2282482 entries, 0 to 2282481
Data columns (total 15 columns):
 #   Column            Dtype
---  ------            -----
 0   SalesKey          int64
 1   DateKey           str
 2   channelKey        int64
 3   StoreKey          int64
 4   ProductKey        int64
 5   PromotionKey      int64
 6   UnitCost          float64
 7   UnitPrice         float64
 8   SalesQuantity     int64
 9   ReturnQuantity    int64
 10  ReturnAmount      float64
 11  DiscountQuantity  int64
 12  DiscountAmount    float64
 13  TotalCost         float64
 14  SalesAmount       float64
dtypes: float64(6), int64(8), str(1)
memory usage: 261.2 MB

- Datekey wordt als string weergegeven, deze dient nog omgezet te worden naar een tijdreeks.
- UnitCost, UnitPrice, TotalCost en SalesAmount werden als strings geïnterpreteerd, door middel van decimal ingeven bij import gecorrigeeerd..

In [62]:
sales_df.head(20)
#De eerste 20 rijn tonen met waarden.

,SalesKey,DateKey,channelKey,StoreKey,ProductKey,PromotionKey,UnitCost,UnitPrice,SalesQuantity,ReturnQuantity,ReturnAmount,DiscountQuantity,DiscountAmount,TotalCost,SalesAmount
0,2201,"2011-05-07 00:00:00,000",1,76,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
1,26527,"2013-05-22 00:00:00,000",1,26,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
2,26702,"2013-09-30 00:00:00,000",1,298,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
3,33125,"2012-10-31 00:00:00,000",1,264,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
4,52306,"2013-06-26 00:00:00,000",1,98,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
5,67230,"2012-10-28 00:00:00,000",1,194,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
6,79246,"2012-05-12 00:00:00,000",1,230,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
7,87210,"2013-04-17 00:00:00,000",1,84,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
8,91129,"2013-05-26 00:00:00,000",1,215,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
9,109148,"2013-04-06 00:00:00,000",1,93,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
10,140079,"2011-04-20 00:00:00,000",1,160,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
11,150342,"2013-06-12 00:00:00,000",1,99,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
12,155121,"2013-06-05 00:00:00,000",1,287,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
13,175299,"2013-06-23 00:00:00,000",1,41,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
14,185802,"2013-05-12 00:00:00,000",1,92,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
15,189564,"2011-10-24 00:00:00,000",1,265,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
16,190221,"2013-04-30 00:00:00,000",1,37,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
17,191830,"2013-06-14 00:00:00,000",1,23,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
18,196400,"2012-05-29 00:00:00,000",1,140,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0
19,207348,"2013-09-17 00:00:00,000",1,301,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.4,6990.0

Datekey lijkt een datumwaarde te moeten zijn, deze moet bij het opschonen van de data omgezet worden.  
UnitCost, UnitPrice, TotalCost en SalesAmount lijkt om bedragen te gaan. De stuksprijs maal de quantity is hier ook gelijk aan de Totalcost en SalesAmount.  
Gezien er geen strings in de tabel zitten ook geen noodzaak om te controleren of deze afwijken van elkaar in schrijfwijze.

In [63]:
sales_df.tail(20)
#Laatste 20 waarden bekijken.

,SalesKey,DateKey,channelKey,StoreKey,ProductKey,PromotionKey,UnitCost,UnitPrice,SalesQuantity,ReturnQuantity,ReturnAmount,DiscountQuantity,DiscountAmount,TotalCost,SalesAmount
2282462,3366917,"2011-06-28 00:00:00,000",1,120,613,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282463,3367028,"2011-05-20 00:00:00,000",1,12,320,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282464,3369192,"2012-05-15 00:00:00,000",1,60,320,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282465,3369889,"2013-04-29 00:00:00,000",1,167,201,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282466,3369908,"2012-10-06 00:00:00,000",1,115,405,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282467,3370934,"2012-04-21 00:00:00,000",1,142,624,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282468,3371111,"2013-05-23 00:00:00,000",1,21,345,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282469,3372220,"2011-05-29 00:00:00,000",1,2,613,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282470,3378122,"2011-06-25 00:00:00,000",1,243,405,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282471,3378463,"2013-10-26 00:00:00,000",1,282,345,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282472,3382789,"2013-07-12 00:00:00,000",1,238,403,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282473,3383821,"2013-10-20 00:00:00,000",1,70,369,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282474,3385816,"2012-04-04 00:00:00,000",1,157,405,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282475,3388423,"2013-06-27 00:00:00,000",1,67,391,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282476,3390532,"2012-04-07 00:00:00,000",1,180,635,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282477,3392414,"2013-05-15 00:00:00,000",1,40,397,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282478,3395082,"2013-10-04 00:00:00,000",1,52,565,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282479,3396997,"2011-07-26 00:00:00,000",1,303,381,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282480,3398163,"2013-07-04 00:00:00,000",1,247,201,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282481,3403155,"2011-05-06 00:00:00,000",1,167,369,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0

Laatste 20 rijen laten hetzelfde patroon zien. In deze rijen zitten ook returns verwerkt. Deze lijken wel goed verwerkt te worden in de TotalCost, bijvoorbeeld 10 items verkocht - 1 return = 9* unitcost.  
Op salesniveau lijkt dit echter niet correct doorberekend. De SalesAmount blijft gelijk aan 10 maal de UnitPrice, ondanks de return.  
Onderzoeken of dit elders wordt opgevangen.

In [64]:
sales_df.describe()

,SalesKey,channelKey,StoreKey,ProductKey,PromotionKey,UnitCost,UnitPrice,SalesQuantity,ReturnQuantity,ReturnAmount,DiscountQuantity,DiscountAmount,TotalCost,SalesAmount
count,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06,2.282482e+06
mean,1.703424e+06,1.627063e+00,1.963849e+02,8.811926e+02,8.498340e+00,1.245984e+02,2.971792e+02,1.616679e+01,1.429619e-01,4.256032e+01,1.476230e+00,5.551586e+01,1.556379e+03,3.654454e+03
std,9.831530e+05,1.028135e+00,9.553847e+01,5.094803e+02,8.258284e+00,1.267489e+02,3.473084e+02,3.935030e+01,3.599263e-01,1.720155e+02,1.798820e+00,1.390498e+02,1.888546e+03,4.853793e+03
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.800000e-01,9.500000e-01,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.920000e+00,3.040000e+00
25%,8.518095e+05,1.000000e+00,1.210000e+02,4.530000e+02,1.000000e+00,3.058000e+01,6.600000e+01,9.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.214800e+02,6.584220e+02
50%,1.704424e+06,1.000000e+00,2.000000e+02,8.800000e+02,4.000000e+00,8.737000e+01,2.000000e+02,1.000000e+01,0.000000e+00,0.000000e+00,1.000000e+00,2.415000e+00,9.860400e+02,2.293600e+03
75%,2.554565e+06,2.000000e+00,2.960000e+02,1.273000e+03,1.400000e+01,1.626400e+02,3.580000e+02,1.300000e+01,0.000000e+00,0.000000e+00,3.000000e+00,5.398000e+01,2.065230e+03,4.699700e+03
max,3.406089e+06,4.000000e+00,3.100000e+02,2.517000e+03,2.800000e+01,9.608200e+02,2.899990e+03,2.880000e+03,5.000000e+00,9.996000e+03,2.400000e+01,6.497400e+03,8.411520e+04,2.354670e+05

In [65]:
sales_df.isna().sum()
#Controleren op lege waarden in cellen. Dit is niet van toepassing.
sales_df.nunique() 
#Aantal unique waarden opsommen.

SalesKey            2282482
DateKey                1096
channelKey                4
StoreKey                306
ProductKey             1689
PromotionKey             28
UnitCost                397
UnitPrice               350
SalesQuantity            98
ReturnQuantity            6
ReturnAmount            782
DiscountQuantity         23
DiscountAmount         8572
TotalCost             14114
SalesAmount           51717
dtype: int64

In [66]:
sales_df[sales_df.duplicated()]
#Checken op duplicated rows

Empty DataFrame
Columns: [SalesKey, DateKey, channelKey, StoreKey, ProductKey, PromotionKey, UnitCost, UnitPrice, SalesQuantity, ReturnQuantity, ReturnAmount, DiscountQuantity, DiscountAmount, TotalCost, SalesAmount]
Index: []

Op basis van bovenstaande analyses zijn er geen lege waardes of duplicaten aanwezig in deze dataset.

De volgende keys dienen gecontroleerd te worden op aanwezigheid in de andere dataset:
- 4 verkoopkanalen volgens sales set.
- 306 unieke winkels volgens sales set.
- 1689 soort producten
- 28 promoties
- 783 retourregels

### 1.3 Corrigeren datatypes

Op basis van de analyse zien we dat de datum gegevens nu niet als juiste dtype worden ingegeven.  
In dit onderdeel worden deze omgezet naar bruikbaar datums.

In [67]:
sales_df2 = sales_df.copy()
#Dataframe kopieeëren als backup 
sales_df2

,SalesKey,DateKey,channelKey,StoreKey,ProductKey,PromotionKey,UnitCost,UnitPrice,SalesQuantity,ReturnQuantity,ReturnAmount,DiscountQuantity,DiscountAmount,TotalCost,SalesAmount
0,2201,"2011-05-07 00:00:00,000",1,76,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
1,26527,"2013-05-22 00:00:00,000",1,26,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
2,26702,"2013-09-30 00:00:00,000",1,298,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
3,33125,"2012-10-31 00:00:00,000",1,264,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
4,52306,"2013-06-26 00:00:00,000",1,98,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282477,3392414,"2013-05-15 00:00:00,000",1,40,397,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282478,3395082,"2013-10-04 00:00:00,000",1,52,565,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282479,3396997,"2011-07-26 00:00:00,000",1,303,381,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282480,3398163,"2013-07-04 00:00:00,000",1,247,201,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282481,3403155,"2011-05-06 00:00:00,000",1,167,369,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0

In [68]:
sales_df2["DateKey"] = pd.to_datetime(sales_df2["DateKey"], format="%Y-%m-%d %H:%M:%S,%f")
#Omzetten naar datetime van DateKey
display(sales_df2)

,SalesKey,DateKey,channelKey,StoreKey,ProductKey,PromotionKey,UnitCost,UnitPrice,SalesQuantity,ReturnQuantity,ReturnAmount,DiscountQuantity,DiscountAmount,TotalCost,SalesAmount
0,2201,2011-05-07,1,76,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
1,26527,2013-05-22,1,26,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
2,26702,2013-09-30,1,298,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
3,33125,2012-10-31,1,264,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
4,52306,2013-06-26,1,98,375,1,321.44,699.0,10,0,0.0,0,0.0,3214.40,6990.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282477,3392414,2013-05-15,1,40,397,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282478,3395082,2013-10-04,1,52,565,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282479,3396997,2011-07-26,1,303,381,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282480,3398163,2013-07-04,1,247,201,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0
2282481,3403155,2011-05-06,1,167,369,1,321.44,699.0,10,1,699.0,0,0.0,2892.96,6990.0

In [69]:
print(sales_df2.loc[sales_df2["DateKey"].idxmin(),"DateKey"])
print(sales_df2.loc[sales_df2["DateKey"].idxmax(),"DateKey"])
#Kijken naar begin en einddatum van dataset.

2011-01-01 00:00:00
2013-12-31 00:00:00

De dataset loopt van 1 januari 2011 tot en met 31 december 2013

In [70]:
datesales = sales_df2.set_index("DateKey")

In [71]:
datesales.resample("ME").agg(aantal_keys=("SalesKey","nunique"),
                             verkoopkanalen=("channelKey","nunique"),
                             kosten=("TotalCost","sum"),
                             SalesAmount=("SalesAmount","sum")
                             ).round(2)

            aantal_keys  verkoopkanalen        kosten   SalesAmount
DateKey
2011-01-31        73868               4  8.159359e+07  1.933056e+08
2011-02-28        70212               4  8.841217e+07  2.094391e+08
2011-03-31        73596               4  8.690551e+07  2.039920e+08
2011-04-30        91338               4  1.168721e+08  2.768910e+08
2011-05-31        94223               4  1.222369e+08  2.887495e+08
2011-06-30        92553               4  1.198062e+08  2.831866e+08
2011-07-31        76193               4  1.153630e+08  2.728186e+08
2011-08-31        76085               4  1.115093e+08  2.637803e+08
2011-09-30        74802               4  1.088589e+08  2.572828e+08
2011-10-31        97618               4  1.209788e+08  2.888539e+08
2011-11-30        78135               4  1.322362e+08  3.087528e+08
2011-12-31        82019               4  1.280783e+08  2.973411e+08
2012-01-31        54822               4  7.901714e+07  1.839700e+08
2012-02-29        55896               4  8.169674e+07  1.911069e+08
2012-03-31        54554               4  7.834271e+07  1.833933e+08
2012-04-30        60971               4  9.503651e+07  2.238493e+08
2012-05-31        58439               4  9.277628e+07  2.205023e+08
2012-06-30        56545               4  8.966215e+07  2.144554e+08
2012-07-31        59234               4  1.038595e+08  2.462393e+08
2012-08-31        59407               4  9.783582e+07  2.311896e+08
2012-09-30        57709               4  9.597999e+07  2.279426e+08
2012-10-31        60039               4  8.800764e+07  2.112036e+08
2012-11-30        58528               4  1.058727e+08  2.477066e+08
2012-12-31        60882               4  1.111790e+08  2.608543e+08
2013-01-31        47594               4  8.007695e+07  1.839413e+08
2013-02-28        46896               4  7.832148e+07  1.809544e+08
2013-03-31        47082               4  7.819069e+07  1.809811e+08
2013-04-30        49882               4  9.014879e+07  2.118945e+08
2013-05-31        52684               4  9.909995e+07  2.343038e+08
2013-06-30        50953               4  9.619981e+07  2.278221e+08
2013-07-31        51528               4  9.828383e+07  2.275068e+08
2013-08-31        51939               4  9.540887e+07  2.218763e+08
2013-09-30        50352               4  9.233792e+07  2.148171e+08
2013-10-31        53289               4  9.318058e+07  2.218386e+08
2013-11-30        50511               4  9.805603e+07  2.208523e+08
2013-12-31        52104               4  1.009856e+08  2.276296e+08

## **Voorlopige conclusie**

De sales dataset loopt van 1 januari 2011 tot en met 31 december 2013 en bestaat uit ***2.282.482*** unieke saleskeys.
Het is nog onduidelijk of de return amounts verrekend moeten worden met de SalesAmount, gezien het verschil tussen kosten en opbrengsten bij een retour.

De volgende keys dienen gecontroleerd te worden op aanwezigheid in de andere dataset:
- 4 **verkoopkanalen** volgens sales set.
- 306 **unieke winkels** volgens sales set.
- 1689 soort **producten**
- 28 **promoties**
- 783 **retourregels**

*Actiepunten*:  
- Navragen verrekenen returns.

# 2 ***Analyse product data***
In dit onderdeel wordt de product data set verkend.  
Het eerste doel is om een indruk te krijgen van de inhoud en de grote van de data set.  
Ten tweede wordt er gecontroleerd op eventuele afwijkende waarden, duplicaten, en missende waarden.  
Uiteindelijk wordt er ook gekeken naar de link met de sales data set. Naar verwachting zijn er minimaal 1689 producten in de dataset.

### 2.1 Importeren dataset
De dataset wordt geimporteerd met behulp van pandas en path.

In [72]:
product_path= Path(r"Data\Contoso_Product.csv")
#Inlezen sales.csv
product_df = pd.read_csv(product_path,
                       decimal=",")

### 2.2 Analyseren product dataset

In [73]:
init_analyse(product_df)
#Functie aanhalen uit shared.py geschreven om te voorkoemn dat telkens dezelfde stappen doorlopen hoeven te worden.

informatie over dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 1690 entries, 0 to 1689
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   BrandName              1690 non-null   str
 1   ClassName              1690 non-null   str
 2   Manufacturer           1690 non-null   str
 3   ProductDescription     1690 non-null   str
 4   ProductKey             1690 non-null   int64
 5   ProductName            1690 non-null   str
 6   ProductSubcategoryKey  1690 non-null   int64
 7   UnitCost               1690 non-null   str
 8   UnitPrice              1690 non-null   str
dtypes: int64(2), str(7)
memory usage: 119.0 KB

aantal gedupliceerde rijen: {df.duplicated().sum()}

Overzicht van lege waarden:

BrandName                0
ClassName                0
Manufacturer             0
ProductDescription       0
ProductKey               0
ProductName              0
ProductSubcategoryKey    0
UnitCost                 0
UnitPrice                0
dtype: int64

Eerste 20 rijen:

,BrandName,ClassName,Manufacturer,ProductDescription,ProductKey,ProductName,ProductSubcategoryKey,UnitCost,UnitPrice
0,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, product type digital camera - ...",951,A. Datum Consumer Digital Camera E100 Black,23,"$143,26",$281
1,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, product type digital camera - ...",965,A. Datum Consumer Digital Camera E100 Grey,23,"$143,26",$281
2,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, product type digital camera - ...",979,A. Datum Consumer Digital Camera E100 Pink,23,"$143,26",$281
3,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, product type digital camera - ...",993,A. Datum Consumer Digital Camera E100 Silver,23,"$143,26",$281
4,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, product type digital camera - ...",1007,A. Datum Consumer Digital Camera E100 Orange,23,"$143,26",$281
5,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, product type digital camera - ...",1021,A. Datum Consumer Digital Camera E100 Green,23,"$143,26",$281
6,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, product type digital camera - ...",1035,A. Datum Consumer Digital Camera E100 Azure,23,"$143,26",$281
7,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, Product type digital camera - ...",950,A. Datum Super-zoom Digital Camera X300 Black,23,"$96,08",$290
8,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, Product type digital camera - ...",964,A. Datum Super-zoom Digital Camera X300 Grey,23,"$96,08",$290
9,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, Product type digital camera - ...",978,A. Datum Super-zoom Digital Camera X300 Pink,23,"$96,08",$290
10,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, Product type digital camera - ...",992,A. Datum Super-zoom Digital Camera X300 Silver,23,"$96,08",$290
11,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, Product type digital camera - ...",1006,A. Datum Super-zoom Digital Camera X300 Orange,23,"$96,08",$290
12,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, Product type digital camera - ...",1020,A. Datum Super-zoom Digital Camera X300 Green,23,"$96,08",$290
13,A. Datum,Deluxe,A. Datum Corporation,"Digital camera, Product type digital camera - ...",1034,A. Datum Super-zoom Digital Camera X300 Azure,23,"$96,08",$290
14,A. Datum,Economy,A. Datum Corporation,"10.2 In x 3 in x 15.3 in, 2.2 lbs",961,A. Datum Ultra Compact Digital Camera M190 Grey,23,"$75,88",$165
15,A. Datum,Economy,A. Datum Corporation,"10.2 In x 3 in x 15.3 in, 2.2 lbs",975,A. Datum Ultra Compact Digital Camera M190 Pink,23,"$75,88",$165
16,A. Datum,Economy,A. Datum Corporation,"10.2 In x 3 in x 15.3 in, 2.2 lbs",989,A. Datum Ultra Compact Digital Camera M190 Silver,23,"$75,88",$165
17,A. Datum,Economy,A. Datum Corporation,"10.2 In x 3 in x 15.3 in, 2.2 lbs",1003,A. Datum Ultra Compact Digital Camera M190 Orange,23,"$75,88",$165
18,A. Datum,Economy,A. Datum Corporation,"10.2 In x 3 in x 15.3 in, 2.2 lbs",1017,A. Datum Ultra Compact Digital Camera M190 Green,23,"$75,88",$165
19,A. Datum,Economy,A. Datum Corporation,"10.2 In x 3 in x 15.3 in, 2.2 lbs",1031,A. Datum Ultra Compact Digital Camera M190 Azure,23,"$75,88",$165

Laatste 20 rijen:

,BrandName,ClassName,Manufacturer,ProductDescription,ProductKey,ProductName,ProductSubcategoryKey,UnitCost,UnitPrice
1670,Wide World Importers,Regular,Wide World Importers,"High brightness, 1300 ANSI lumen light output,...",626,WWI Projector 480p LCD12 White,19,"$116,75",$229
1671,Wide World Importers,Regular,Wide World Importers,"High brightness, 1300 ANSI lumen light output,...",637,WWI Projector 480p LCD12 Silver,19,"$116,75",$229
1672,Wide World Importers,Regular,Wide World Importers,Listening to music wirelessly with other Bluet...,106,WWI Stereo Bluetooth Headphones New Generation...,6,"$61,16","$132,99"
1673,Wide World Importers,Regular,Wide World Importers,Listening to music wirelessly with other Bluet...,107,WWI Stereo Bluetooth Headphones New Generation...,6,"$61,16","$132,99"
1674,Wide World Importers,Regular,Wide World Importers,Listening to music wirelessly with other Bluet...,108,WWI Stereo Bluetooth Headphones New Generation...,6,"$61,16","$132,99"
1675,Wide World Importers,Regular,Wide World Importers,Listening to music wirelessly with other Bluet...,109,WWI Stereo Bluetooth Headphones New Generation...,6,"$61,16","$132,99"
1676,Wide World Importers,Regular,Wide World Importers,Listening to music wirelessly with other Bluet...,110,WWI Stereo Bluetooth Headphones New Generation...,6,"$61,16","$132,99"
1677,Wide World Importers,Regular,Wide World Importers,"Native 720p resolution, 1700 ANSI lumens, 2500...",614,WWI Projector 720p DLP56 Black,19,"$459,4",$999
1678,Wide World Importers,Regular,Wide World Importers,"Native 720p resolution, 1700 ANSI lumens, 2500...",625,WWI Projector 720p DLP56 White,19,"$459,4",$999
1679,Wide World Importers,Regular,Wide World Importers,"Native 720p resolution, 1700 ANSI lumens, 2500...",636,WWI Projector 720p DLP56 Silver,19,"$459,4",$999
1680,Wide World Importers,Regular,Wide World Importers,"Record and link audio to be written, listen to...",49,WWI 2GB Pulse Smart pen M100 White,4,"$91,95","$199,95"
1681,Wide World Importers,Regular,Wide World Importers,"Record and link audio to be written, listen to...",50,WWI 2GB Pulse Smart pen M100 Black,4,"$91,95","$199,95"
1682,Wide World Importers,Regular,Wide World Importers,"Record and link audio to be written, listen to...",51,WWI 2GB Pulse Smart pen M100 Blue,4,"$91,95","$199,95"
1683,Wide World Importers,Regular,Wide World Importers,"Record and link audio to be written, listen to...",52,WWI 2GB Pulse Smart pen M100 Silver,4,"$91,95","$199,95"
1684,Wide World Importers,Regular,Wide World Importers,"Screen size: 20"", response time: 5ms, brightne...",521,WWI LCD20 M220 Black,18,"$119,11",$259
1685,Wide World Importers,Regular,Wide World Importers,"Screen size: 20"", response time: 5ms, brightne...",532,WWI LCD20 M220 White,18,"$119,11",$259
1686,Wide World Importers,Regular,Wide World Importers,"Wireless range beyond 10 meters, MP3-quality s...",98,WWI Wireless Bluetooth Stereo Headphones M170 ...,6,"$55,18",$120
1687,Wide World Importers,Regular,Wide World Importers,"Wireless range beyond 10 meters, MP3-quality s...",99,WWI Wireless Bluetooth Stereo Headphones M170 ...,6,"$55,18",$120
1688,Wide World Importers,Regular,Wide World Importers,"Wireless range beyond 10 meters, MP3-quality s...",100,WWI Wireless Bluetooth Stereo Headphones M170 ...,6,"$55,18",$120
1689,Wide World Importers,Regular,Wide World Importers,"Wireless range beyond 10 meters, MP3-quality s...",101,WWI Wireless Bluetooth Stereo Headphones M170 ...,6,"$55,18",$120

Uit de eerste analyse blijkt dat er 1690 unique keys in de dataset zitten. Dit sluit aan op de eerdere verwachting dat er minimaal 1689 unieke keys aanwezig dienen te zijn. Er is ook geen sprake van duplicaten op basis van deze analyse. Uit de weergave blijkt dat producten in verschillende kleuren beschikbaar zijn. Dit kan later interessant zijn voor een analyse op welk kleur product het beste/slechtste verkoopt. 

Gekeken naar de datatypes zou de verwachting zijn dat de UnitCost en Unitprice als floats zouden worden ingeladen. Dit lijkt voorkomen te worden door de dollartekens in de cellen. Dit dienen we nog op te schonen. 

In de hele product dataset komen geen lege waarden voor.

De eerste stap is om de kosten en prijs om te zetten naar decimale waarden. Hiermee kunnen we ook controleren of de kosten en prijs in de product dataset gelijk zijn aan die in de sales dataset.

In [74]:
product_df["UnitCost"] = product_df["UnitCost"].str.removeprefix("$").str.replace(",",".")
product_df["UnitPrice"] = product_df["UnitPrice"].str.removeprefix("$").str.replace(",",".")
#Verwijderen van de $ prefixes uit de kolommen UnitCost en UnitPrice. Daarna de komma vervangen om floats te kunnen maken.

In [75]:
product_df[["UnitCost","UnitPrice"]] = product_df[["UnitCost","UnitPrice"]].apply(pd.to_numeric)
#UnitCost en UnitPrice omzetten in floats.

In [76]:
product_df.info()
#Controleren of waarden zijn omgezet.

<class 'pandas.DataFrame'>
RangeIndex: 1690 entries, 0 to 1689
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   BrandName              1690 non-null   str
 1   ClassName              1690 non-null   str
 2   Manufacturer           1690 non-null   str
 3   ProductDescription     1690 non-null   str
 4   ProductKey             1690 non-null   int64
 5   ProductName            1690 non-null   str
 6   ProductSubcategoryKey  1690 non-null   int64
 7   UnitCost               1690 non-null   float64
 8   UnitPrice              1690 non-null   float64
dtypes: float64(2), int64(2), str(5)
memory usage: 119.0 KB

In [77]:
product_df.loc[~product_df["ProductKey"].isin(sales_df["ProductKey"])]
#Zoeken naar producten wel in product dataset maar niet in de salesdata set

,BrandName,ClassName,Manufacturer,ProductDescription,ProductKey,ProductName,ProductSubcategoryKey,UnitCost,UnitPrice
35,A. Datum,Economy,A. Datum Corporation,"Digital camera, 3.7 in x 0.9 in x 2",944,A. Datum Compact Digital Camera M200 Black,23,59.32,129.0

De A. Datum Comapct Digital Camera M200 black zit wel in de product dataset maar wordt volgens de sales data niet verkocht.

In [78]:
display(product_df.nunique())
#Aantal unieke eigenschappen onderzoeken.

BrandName                  10
ClassName                   3
Manufacturer               10
ProductDescription        516
ProductKey               1690
ProductName              1690
ProductSubcategoryKey      22
UnitCost                  397
UnitPrice                 350
dtype: int64

In [79]:
#Onderzoeken van strings op verschillende soorten en eventuele dubbel aanwezige gegevens met afwijkende schrijfwijzes.

display(product_df["BrandName"].value_counts())
#Onderzoeken producten van ieder merk
display(product_df["ClassName"].value_counts())
#Onderzoeken segmenten
display(product_df["Manufacturer"].value_counts())
#Onderzoeken Producenten
display(product_df["ProductDescription"].value_counts())
#Onderzoeken productomschrijvingen
display(product_df["ProductName"].value_counts())
#Onderzoeken productnamen

BrandName
Contoso                 560
Proseware               177
Southridge Video        170
Fabrikam                163
The Phone Company       152
Wide World Importers    133
A. Datum                132
Adventure Works         128
Litware                  48
Northwind Traders        27
Name: count, dtype: int64

ClassName
Regular    930
Economy    516
Deluxe     244
Name: count, dtype: int64

Manufacturer
Contoso, Ltd            560
Proseware, Inc.         177
Southridge Video        170
Fabrikam, Inc.          163
The Phone Company       152
Wide World Importers    133
A. Datum Corporation    132
Adventure Works         128
Litware, Inc.            48
Northwind Traders        27
Name: count, dtype: int64

ProductDescription
1080i/p or 720p high definition or standard definition                                             35
6-hour rechargeable battery, 180-degree swivel and flip screen                                     30
Store your CDs or DVDs in these beautiful binders, designed to look like books                     24
Digital camera - SLR with live view mode                                                           21
720p high definition or VGA                                                                        20
                                                                                                   ..
16:9 Aspect Ratio - 113in.Dual wall and ceiling - perfect for home / business.                      1
16:9 Aspect Ratio - 125in. 160 degree wide viewing angle.                                           1
16:9 aspect ratio-113in, dual wall and ceiling - perfect for home / business                        1
2.3GHz dual processor, 4 GB DDR2 SDRAM memories, 4MB L2 Cache                                       1
3.0GHz processor, 4 GB DDR2 SDRAM memories, 500GB 7200RPM hard drive, 19 inch LCD flat monitors     1
Name: count, Length: 516, dtype: int64

ProductName
A. Datum Consumer Digital Camera E100 Black             1
A. Datum Consumer Digital Camera E100 Grey              1
A. Datum Consumer Digital Camera E100 Pink              1
A. Datum Consumer Digital Camera E100 Silver            1
A. Datum Consumer Digital Camera E100 Orange            1
                                                       ..
WWI LCD20 M220 White                                    1
WWI Wireless Bluetooth Stereo Headphones M170 Silver    1
WWI Wireless Bluetooth Stereo Headphones M170 Black     1
WWI Wireless Bluetooth Stereo Headphones M170 White     1
WWI Wireless Bluetooth Stereo Headphones M170 Pink      1
Name: count, Length: 1690, dtype: int64

De verschillende merken, segmenten, producenten, productomschrijvingen en productnamen zijn geanalyseerd.
Hier komen geen dubbele waarde in voor veroorzaakt door afwijkende schrijfwijzen.   

Opvallend is het feit dat er **516** unieke descripties zijn van producten, maar **1690** unieke productbenamingen.
Dit wordt met name veroorzaakt door het feit dat iedere product meerdere kleurvarianten heeft.   

Het lijkt aan te raden om een scheiding te maken tussen productnamen en kleuren. 
Zo kan er zuiver gekeken worden naar productverkopen en later naar de voorkeur van de kleur. 
De verwachting is dat na opschonen het aantal unieke productnamen zonder kleur gelijk is aan de unieke productomschrijvingen.

De volgende stap is om te kijken of product kosten en prijzen overeenkomen met de gegevens uit de sales set.

In [80]:
sales_df["ProductUnitCost"] = sales_df["ProductKey"].map(
    product_df.set_index("ProductKey")["UnitCost"]
)

sales_df["CostControl"] = (
    sales_df["ProductUnitCost"] == sales_df["UnitCost"]
)

In [81]:
sales_df[~sales_df["CostControl"]]
#Controleren waar UnitCost niet overeenkomt.

Empty DataFrame
Columns: [SalesKey, DateKey, channelKey, StoreKey, ProductKey, PromotionKey, UnitCost, UnitPrice, SalesQuantity, ReturnQuantity, ReturnAmount, DiscountQuantity, DiscountAmount, TotalCost, SalesAmount, ProductUnitCost, CostControl]
Index: []

In [82]:
sales_df["ProductUnitPrice"] = sales_df["ProductKey"].map(
    product_df.set_index("ProductKey")["UnitPrice"]
)

sales_df["PriceControl"] = (
    sales_df["ProductUnitPrice"] == sales_df["UnitPrice"]
)

In [ ]:
sales_df[~sales_df["PriceControl"]]
#Onderzoeken waar prijs niet overeenkomt.

Empty DataFrame
Columns: [SalesKey, DateKey, channelKey, StoreKey, ProductKey, PromotionKey, UnitCost, UnitPrice, SalesQuantity, ReturnQuantity, ReturnAmount, DiscountQuantity, DiscountAmount, TotalCost, SalesAmount, ProductUnitCost, CostControl, ProductUnitPrice, PriceControl]
Index: []

Uit vergelijkingen met de sales dataset blijkt dat kosten en prijzen voor alle sales overeenkomen met die uit de productdata.